# coding: utf-8

"""
    Kingpick ImageMatch API

    Image Perceptual Hash services. Search for images that look similar to each other.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cvtool_image_hashes_client
from cvtool_image_hashes_client.rest import ApiException
from cvtool_image_hashes_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = cvtool_image_hashes_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_add(self):
        """
        Test case for add

        
        """
        pass

    def test_search(self):
        """
        Test case for search

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
