# coding: utf-8

"""
    Kingpick ImageMatch API

    Image Perceptual Hash services. Search for images that look similar to each other.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ImageHashRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, filepath=None, url=None, metadata=None):
        """
        ImageHashRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'filepath': 'str',
            'url': 'str',
            'metadata': 'Metadata'
        }

        self.attribute_map = {
            'filepath': 'filepath',
            'url': 'url',
            'metadata': 'metadata'
        }

        self._filepath = filepath
        self._url = url
        self._metadata = metadata

    @property
    def filepath(self):
        """
        Gets the filepath of this ImageHashRequest.
        The path to save the image to in the database. If another image already exists at the given path, it will be overwritten.

        :return: The filepath of this ImageHashRequest.
        :rtype: str
        """
        return self._filepath

    @filepath.setter
    def filepath(self, filepath):
        """
        Sets the filepath of this ImageHashRequest.
        The path to save the image to in the database. If another image already exists at the given path, it will be overwritten.

        :param filepath: The filepath of this ImageHashRequest.
        :type: str
        """

        self._filepath = filepath

    @property
    def url(self):
        """
        Gets the url of this ImageHashRequest.
        The image to add to the database.

        :return: The url of this ImageHashRequest.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this ImageHashRequest.
        The image to add to the database.

        :param url: The url of this ImageHashRequest.
        :type: str
        """

        self._url = url

    @property
    def metadata(self):
        """
        Gets the metadata of this ImageHashRequest.

        :return: The metadata of this ImageHashRequest.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """
        Sets the metadata of this ImageHashRequest.

        :param metadata: The metadata of this ImageHashRequest.
        :type: Metadata
        """

        self._metadata = metadata

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ImageHashRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
